### ISSUE TITLE
Fraud attempt message in our emails

### ISSUE THREAD

**Issue by Domtreas** [MailScanner/v5#11]
Firstly apologies first if this is the wrong place to place message. 

We have been notified that Mailscanner is posting inaccurate messages in prospects emails regards fraud attempts. 

We (Regus) use a white label SMTP service (Mandrillapp) to deliver prospecting emails responding to web enquiries with SPF and DKIM verification in place. How do we remove fraud attempt messaging from appearing?

![image001](https://cloud.githubusercontent.com/assets/20224278/16486492/eda4572e-3ebc-11e6-906d-78d966e6b656.jpg)
0

**Comment by jcbenton** [comment]
You have a link with a different domain displayed, which is considered fraud.

Example:

< \a href=“domain.com” > domain.net < / a >


In this example the domains do not match.  It is considered a
fraudulent link. Fix your links.


-
Jerry Benton
www.mailborder.com
+1 - 844-436-6245


-----Original Message-----

**Comment by Domtreas** [comment]
Jerry - thanks for speedy response. Appreciate your help. will get tech team to investigate.

**Comment by Domtreas** [comment]
Jerry,

Just talked to tech team - the link is a tracking link, for example:

http://mandrillapp.com/track/click/30350882/www.regus.de?p=eyJzIjoiSndHZW9yZ3VWelBsNkEzLVdRcWZpdlNjTk5nIiwidiI6MSwicCI6IntcInVcIjozMDM1MDg4MixcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3LnJlZ3VzLmRlP3Q9X35MZWFkX1JlZmVyZW5jZV9OdW1iZXJ-X35QTl9yZWZlcmVuY2VfTnVtYmVyflwiLFwiaWRcIjpcIjQ0YmQ2N2I2NWIxZTQ0MDI5ZjI2NTcwMTE5MTA2OTk1XCIsXCJ1cmxfaWRzXCI6W1wiMzk5NWY1MDRjNmI2Njk2MDBlYTQ3MjJhZjdhMDVlNGNjZTI2YzFkMlwiXX0ifQ

You are correct the href doesn't match the text displayed, So how do we keep tracking links in place, as we need reporting?  We can't be the first company to deploy tracking links? How do you advise

**Comment by jcbenton** [comment]
You can disable the phishing checks. However, that does not mean other
sites will not freak out on the same check and still mark it as fraud.
Some sites will kill the 1x1 image because that is obviously a
tracking image. Some sites will even kill the email all together.
MailScanner calls these 1x1’s web bugs.

Most people you talk to in the open source community, or the security
community, (which is me in both cases) will agree tracking is sneaky,
intrusive, and generally just evil. I understand the marketing
benefits it can have, but I still do not use it in my commercial
business. I have been able to grow my business without being a sneaky
bastard. Other companies can do the same.

I, like many others, see it as an invasion of privacy. It is also a
method for harvesting email addresses. If I want people to know I read
their emails, I would reply to them.

Of course, this will fall on deaf ears in the marketing department.

-
Jerry Benton
www.mailborder.com
+1 - 844-436-6245


-----Original Message-----
