### ISSUE TITLE
ruesets (help wanted)

### ISSUE THREAD

**Issue by ghost235** [MailScanner/v5#155]
Hi @ all,

I've aquestion to the rulesets. Let's say filename / filetype rules looks like this.

#Rule for Mailwatch release
From:  127.0.0.1  /etc/MailScanner/filename.rules.quarantaene.conf 

#Rule for domain1 to block .docx .exe .com .....
To:                  domain1.net                        /etc/MailScanner/filename.rules.conf 

#Rule for domain2 to block .exe .com ..... but without blocking .docx
FromOrTo       domain2.com                       /etc/MailScanner/filename.rules.office.conf

#default rule for to block .docx .exe .com .....
FromOrTo:       default                                 /etc/MailScanner/filename.rules.conf

First the To: domain1.net rule is to block .docx from domain2.com because when I don't add this rule domain2.com can send .docx to domain1.net.
But when I (with this ruleset) release a .docx from Mailwatch for domain1.net it will be blocked again.
Why? I thougt the first match in a rulset is used.

**Comment by Skywalker-11** [comment]
Depending on your server configuration MailWatch may use IPv6. Have you tried to add a rule with ::1?

**Comment by msapiro** [comment]
Both Filename Rules and Filetype Rules are "All Match" rulesets. See, e.g., https://www.mailscanner.info/MailScanner.conf.index.html#Filename%20Rules

**Comment by ghost235** [comment]
FUCK !! This ist the kind of guys I want to work with!

@Skywalker-11 : nice suggestion I'll add this on demand, thanks.

but I think the hint from msapiro is my real problem. Thanks for that @msapiro I was blind. ;)

Is there any solution for this situation?

domain1.net  - don't want .docx
domain2.com - want .docx
127.0.0.1/::1 - should resease .docx also to domain1.net
but 
domain2.com is not allowed to send .docx to domain1.net

p.s. the server holds ~ 150 domains i.e. a rule for every combination of domains is NOT the sulution ;)

**Comment by shawniverson** [comment]
Hang on @ghost235 , I think this should work, actually,

"All Match" refers to the matching against all recipients in addition to the first match.  It doesn't have anything to do with the order of the rulesets.

From the top of https://www.mailscanner.info/MailScanner.conf.index.html#Filename%20Rules
```
"All Match" rulesets work through every recipient, concatenating all the results. "All Match" rulesets are usually used when you want to check if any of the recipient addresses match. For example, when evaluating a "Yes/No" option with an "All Matches" ruleset, the result is taken as a "Yes" if any of the addresses match at all.
```

In fact, I just tested this on my system as follows.

/etc/MailScanner/filename.rules
```
From:   127.0.0.1       /etc/MailScanner/filename.rules.allowall.conf
From:   ::1       /etc/MailScanner/filename.rules.allowall.conf
To:     example.org  /etc/MailScanner/test1.rules.conf
FromOrTo:       default /etc/MailScanner/filename.rules.conf
```

/etc/mailScanner/filename.rules.allowall.conf
```
allow   .*      -       -
```

/etc/MailScanner/test1.rules.conf
```
deny    /\.docx$/       -       -
```

/etc/MailScanner/filename.rules.conf
```
allow    /\.docx$/       -       -
```

So, I sent an email with a docx to example.org.  It was blocked, which means the third ruleset was evaluated and stopped processing.  I released it successfully, meaning the first or second rule file was evaluated and stopped processing the ruleset.

I made sure of the following so that the docx was actually quarantined.

/etc/MailScanner/MailScanner.conf
```
Quarantine Infections = yes
```

I'm guessing you are using MailWatch.  If so, this must be disabled because attachments are stored as-is.  They will not release using sendmail and/or postfix.sendmail:
/path/to/conf.php
```
define('QUARANTINE_USE_SENDMAIL', false);
```

**Comment by ghost235** [comment]
Thanks @shawniverson 

I added in the .conf for 127.0.0.1 / ::1 the allow for .docx this fixes the issue.

Bevor I only hadn't a "deny" with the explicite "allow" all is fine. 

THANKS @ all
