### ISSUE TITLE
A few suggestions by install script (Red Hat / CentOS)

### ISSUE THREAD

**Issue by ssgu85** [MailScanner/v5#16]
Hi!

Advance sorry for my English.

I have a few suggestions by install script on Red Hat / CentOS OS.

1. In section, where checking perl modules and trying install it with YUM, in string
`THING="'perl($i)'";`
you need to remove the single quotes to get as
`THING="perl($i)";`
otherwise YUM would not be able to find packages

2. EPEL repo for RHEL7 already contains packages perl-Filesys-Df and perl-Sys-Hostname-Long
It was possible to remove a separate section to install this packages for RHEL7?

3. Plase add additional packages to install perl modules with YUM:
`perl-Encode-Detect perl-LDAP perl-IO-Compress-Bzip2`
This packages contents in EPEL repo for RHEL releases (5,6)
`perl-IO-Compress`
This packages contents in basic repo for RHEL releases 7

4. Variable MOREPACKAGES contains twice 'unrar'

Thanks for your attention.

**Comment by jcbenton** [comment]
1. Change it yourself, run it, and see what happens. You have tested this? I don't mean running it on the command line. I mean running it in the script. 

2. It did not contain them when the installer was written. I can add them to the array of Perl items installed via Yum. The check will still remain because it is used over 5,6, and 7. 

3. If they are in all 3 (RHEL 5,6,7) I will add them. Are they?

 4. Fixed.

**Comment by ssgu85** [comment]
1. I tested it from bash script on Centos 5 - 7. With single quotes YUM not found any packages. Without single quotes YUM find and install necessary package.

2. Presently, EPEL repo for all version RHEL (5 ,6 ,7) contains this packages.

3. perl-Encode-Detect is in basic repo RHEL 6,7 and EPEL repo RHEL 5
perl-LDAP is in basic repo RHEL 5,6,7
perl-IO-Compress-Bzip2 is in EPEL repo RHEL 5, basic repo RHEL 6, but perl module of this package on RHEL 7 contains in perl-IO-Compress in basic repo.

Thanks!

**Comment by jcbenton** [comment]
1. updated
2. already attempts to install from REPO first
3. added
