### ISSUE TITLE
ClamAV Supplementary Groups on Ubuntu

### ISSUE THREAD

**Issue by shawniverson** [MailScanner/v5#166]
From list

> Hi,
> I have just installed MailScanner into a new Ubuntu 16.04.4 LTS server
> and updated it to the latests packages.
> Making tests over the new server I have seen that ClamAV is not
> operating fine due to permission problems:
> [...]
> MailScanner[15458]: Virus and Content Scanning: Starting
> MailScanner[15458]: Clamd::ERROR:: UNKNOWN CLAMD RETURN ./lstat()
> failed: Permission denied. ERROR :: /var/spool/MailScanner/incoming/15458
> MailScanner[15458]: Virus Scanning: Clamd found 1 infections
> MailScanner[15458]: Virus Scanning: Found 1 viruses
> [...]
> 
> I have solved the problem modifying the configuration parameter
> AllowSupplementaryGroups from false to true in the file:
> /etc/clamav/clamd.conf
> 
> Please, MailScanner developers, take this into account in the installer
> for Ubuntu for the next release.
> 
> Thank you very much.
> Best regards.

**Comment by thctlo** [comment]
Hai, 

imo, not a bug, but misconfiguration, i'll explain. 
ps, which list??   , i'll add myself there then also. ;-) 

Because on my debian stetch im using mtagroup and not AllowSupplementaryGroups true, 
Thats not even in my config. ubuntu 16.x and debian stretch are 99% the same. 

I've set : 
MailScanner.conf:Incoming Work Group = mtagroup

Now, if you run the following to see the clamav-daemon defaults. ( you need to install it first )

debconf-get-selections | grep clamav-daemon   ( Not working, install debconf-utils )
Then put your values in as defaults as followed : 
echo "clamav-daemon   clamav-daemon/AddGroups string  mtagroup" | debconf-set-selections
dpkg-reconfigure clamav-daemon

And your done. 
Imo the best way to set it and i think this problem is inherited from:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826406 
So in future the option will be removed.

**Comment by shawniverson** [comment]
@thctlo Thanks for clarification.  Closing.
