### ISSUE TITLE
Upgrading to MailScanner-5.1.3-2 generates sudo errors with eset 

### ISSUE THREAD

**Issue by flagmonkey** [MailScanner/v5#365]
After upgrading MailScanner MailScanner-5.1.2-2 to MailScanner-5.1.3-2 on  Ubuntu 18.04 the system generates a massive amount of mails "subject: *** SECURITY information for ***" and body :
 
Debian-exim : user NOT in sudoers ; TTY=unknown ; PWD=/var/spool/MailScanner/incoming/11611 ; USER=root ; COMMAND=/opt/eset/esets/sbin/esets_scan.

The system load quickly raises to double digits.

Is there a known issue with eset (v4.5.11)?

**Comment by shawniverson** [comment]
https://github.com/MailScanner/v5/blob/master/common/usr/lib/MailScanner/wrapper/esets-wrapper-README

**Comment by flagmonkey** [comment]
Thanks for you quick support, can confirm this is a fix for the problem.

**Comment by nerijus** [comment]
Why sudo is needed for esets? It worked without sudo before, what has changed?
esets-wrapper-README is not in the rpm package.

**Comment by nerijus** [comment]
I found discussion at https://forum.efa-project.org/viewtopic.php?p=13115#p13115. The reported problem is:
Using license: LIC HERE (/etc/opt/eset/esets/license/esets_xxxxx.lic)
Scanner initialization failed.

Such problems are permissions problems, user running esets binary (i.e. postfix) probably does not have permissions to access license file, etc. So using sudo for esets wrapper is overkill and bad for security. Please revert it.

**Comment by shawniverson** [comment]
@nerijus Care to share how you configured permissions on esets?  It appears you are running MailScanner as root, which is probably also overkill and bad for security.

**Comment by nerijus** [comment]
I didn't need to configure, my esets version works OK without additional changes. But I remember changing directories and files permissions for another antivirus a few years ago. In this case, you have to check permssions of /etc/opt/eset/esets/license/esets_xxxxx.lic and all the directories, so that postfix user has read permissions, until su postfix -c "/opt/eset/esets/sbin/esets_scan /tmp" works on your system.
Most probably needed permissions (or which group user should belong to) are written in esets manual.

**Comment by nerijus** [comment]
I suggest adding info about permissions or running with sudo to esets-wrapper-README (and add the file to rpm package btw), but remove sudo from esets-wrapper.

**Comment by shawniverson** [comment]
https://github.com/MailScanner/v5/pull/370
