### ISSUE TITLE
Cannot lock /var/spool/MailScanner/incoming/Locks/esetsBusy.lock

### ISSUE THREAD

**Issue by Schroeffu** [MailScanner/v5#383]
I have just upgraded from Mail Scanner v5.0.7-3 to v5.1.3-3 and added at the same time the **ESETS Command Line Virus Scanner** 
(ESETS Product with Command Line Scanner is calling itself: _ESETS Linux File Server Security_)

The following warning appears now in the logfile, but the ESETS scanner is properly detecting viruses:

**`Apr 16 08:44:39 mailserver2 MailScanner[3077]: Cannot lock /var/spool/MailScanner/incoming/Locks/esetsBusy.lock, No such file or directory`**

This _esetsBusy.lock_ file does not exist. Should MailScanner create it by themself?

Many thanks for checking

**Comment by shawniverson** [comment]
SweepViruses.pm, near Line 782
```
 if (open($Lock, ">$VirusLock")) {
    print $Lock  "Virus check locked for " .
          ($disinfect?"disinfect":"scann") . "ing with $scanner $$\n";
  } else {
    #The lock file already exists, so just open for reading
    open($Lock, "<$VirusLock")
      or MailScanner::Log::WarnLog("Cannot lock $VirusLock, $!");
  }
  flock($Lock, $LOCK_SH);
```

What should happen is the first branch of the if, the lock file should be successfully created, and the files/emails scanned.

In your case the lock is failing to be created, so it thinks its because it already exists, and tries to open it, which fails as well.

Therefore, check your permissions and ownership of the /var/spool/MailScanner/incoming/Locks directory branch, and also verify that no mandatory access control is interfering (AppArmor or SELinux)

**Comment by shawniverson** [comment]
Closing for now.  If still having issues, please let me know.
