### ISSUE TITLE
Script tag of application/ld+json detected as malicius but it is not malicius

### ISSUE THREAD

**Issue by carazo** [MailScanner/v5#46]
Good morning,

I have seen in some servers that use MailScanner that it changes the tag "<script>" to "< MailScannerScript686126>" when this tag is used to include application/ld+json data.

How can we try to avoid it?

**Comment by jcbenton** [comment]
This is not a technical issue and it is the wrong place to ask this question. This is a configuration item under dangerous content scanning regarding script tags. FWIW - email should never ever contain script tags.

**Comment by carazo** [comment]
Jerry,

Sorry but currently structured data is the way to include in email information like "departure time" in a formal way.

The standard includes the use of <script> tag but using JSON-LD: https://developers.google.com/search/docs/guides/intro-structured-data

So yes, mail should never include JavaScript but it should allow using it.

**Comment by msapiro** [comment]
As Jerry said, it's a configuration option.

Allow Script Tags = yes

**Comment by carazo** [comment]
Thanks!!

**Comment by jcbenton** [comment]
You may build your application however you see fit. However, it is going to be blocked by just about every email application and provider in the world if you try to include javascript in an email. This includes Google. Javascript is a primary attack vector and no one worth their salt is going to allow it. Email messages are not stand-alone programs and should never attempt to execute anything, which is exactly what javascript does. 

You can include structured data in an email without including the javascript in the email. Your server generates the relevant data and inserts it into the email in either plain text or HTML format. The email itself should not be populating itself with data via javascript. Again, you can design it however you see fit, but just because you put screen doors on your submarines doesn't mean that anyone is going to allow them in their navy.

As Mark said, you can allow script tags. However, as soon as your email hits any respectable server it is going to be either rejected, deleted, or disarmed.

**Comment by carazo** [comment]
@jcbenton 

But this is not any JavaScript, this is JSON-LD and it saves things like it:

{"@context":"http://schema.org/","@type":"Order","url":"https://codection.com/wp-admin/post.php?post=5546&action=edit","orderStatus":"","orderNumber":"5546","orderDate":"2017-04-05T09:13:33+00:00","acceptedOffer":

Never JavaScript.

The problem is that it uses the same tag :(

**Comment by jcbenton** [comment]
It only fires when it sees a <script> tag.  The code you posted is fine and will not cause it to fire.

**Comment by carazo** [comment]
Jerry,

I think you are not understanding. The standard is at follows:

<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "http://www.your-company-site.com",
  "contactPoint": [{
    "@type": "ContactPoint",
    "telephone": "+1-401-555-1212",
    "contactType": "customer service"
  }]
}
</script>

As you can see here: https://developers.google.com/search/docs/guides/intro-structured-data

The script tag with this attribute-value should always be approved: type="application/ld+json"

I have never said I will include JS in a email (I am not mad).

**Comment by jcbenton** [comment]
Ok, we can look at an exclusion for <script type="application/ld+json"> but I will have to research it.

**Comment by carazo** [comment]
Ok, sorry I think you have thought that a <script> tags is only for JS.

Currently we are working hard in semantic web and this kind of information is basic for example when you book a flight and Gmail later now "reading your email" when and where is the depart, the arrive, etc.

**Comment by jcbenton** [comment]
Mark,

I am looking at SweepContent.pm lines 494 to 595. I have got some ideas. Email me when you have time to talk.

**Comment by jcbenton** [comment]
carazo -

I have tested this locally using what I have available. Can you test this since you have a system that generates the email in question?

set this: 
Allow Script Tags = no
in your MailScanner.conf

Replace your SweepContent.pm with the attached file. (You have to rename it .pm and save the old one before overwriting.) If you are using the latest version of MailScanner, it should be in /usr/share/MailScanner/perl/MailScanner

restart mailscanner before testing.

[SweepContent.pm.txt](https://github.com/MailScanner/v5/files/900318/SweepContent.pm.txt)

**Comment by carazo** [comment]
Ok perfect, I am going to talk with my ISP.

**Comment by carazo** [comment]
No, my hosting does not want to do the test.

I cannot help you with it. Sorry.

**Comment by jcbenton** [comment]
Who is the hosting company? I'd like to make a mental note for the next time they ask the open source community for help. 

Can you attach a raw copy of an email you are having problems with? I will try to test it.

**Comment by jcbenton** [comment]
Or you can zip it up and email it to me directly.

**Comment by carazo** [comment]
I cannot tell you the hosting name, sorry, they are my partners and my colleague does not allow me.

I cannot send you it because of the ones with problems are all orders in a shop and they are full of personal and private data.

Basically you have to add in the content this and try:

<script type="application/ld+json"> { "@context": "http://schema.org", "@type": "Organization", "url": "http://www.your-company-site.com", "contactPoint": [{ "@type": "ContactPoint", "telephone": "+1-401-555-1212", "contactType": "customer service" }] } </script>

If the JSON-LD text is transformed or it is kept into the script tag.

**Comment by jcbenton** [comment]
This is implemented.
