### ISSUE TITLE
MailScanner has detected a possible fraud attempt

### ISSUE THREAD

**Issue by soyelfede** [MailScanner/v5#504]
A client has responded to an email and I see that the legend appears (I transcribe the text of the email with the alert message): 
_We are pleased to inform you that the call for the Silos Foundation Short Stories Award is already published in Cultural Resources. You can see it and share it on the networks from the following link: https://www.recursosculturales.com/?p=103050_ 
**MailScanner has detected a possible fraud attempt from "r.email-recursosculturales.com" claiming to be https://www.recursosculturales.com/?p=103050**

_r.email-recursosculturales.com_ seems to be a redirect added by my mailing provider, Sendinblue, to track clicks on my email links. 
Is there any solution for this?

Best regards

**Comment by msapiro** [comment]
What is actually happening is the original html behind the text you quote above is something like:

We are pleased to inform you that the call for the Silos Foundation Short Stories Award is already published in Cultural Resources. You can see it and share it on the networks from the following link: <a href="https://r.email-recursosculturales.com/...>https://www.recursosculturales.com/?p=103050</a>

MailScanner running somewhere in the delivery chain between the addition of that text and the recipient detects that the displayed URL's domain, www.recursosculturales.com is different from the target domain, r.email-recursosculturales.com and adds the phishing fraud warning.

If you have control over the MailScanner that added the warning, you can configure it not to. If you have control over the process that adds the legend you quote, you can try to ensure that the domain in the displayed link is the same as the domain in the target or just not add it. If not, perhaps you can get whoever does control that to ensure that the domain in the displayed link is the same as the domain in the target or just not add it.

Otherwise, there's nothing you can do.

**Comment by soyelfede** [comment]
Thanks for the explanation

This would then be fixed if I use, for example?
_You can see it and share it on the networks from <a href="https://www.recursosculturales.com/"> the following link </a>_

That way the code with the link only contains a single domain

**Comment by msapiro** [comment]
Yes, The think that triggers the warning is the displayed text of the link looks like a URL but had a domain which is different (modulo a 'www'`) from the target domain. If the link text doesn't look like a URL, it won't be flagged.

**Comment by soyelfede** [comment]
Perfect! Thanks for your help.
