### ISSUE TITLE
Accept IPv6 addresses in patterns for rules.

### ISSUE THREAD

**Issue by msapiro** [MailScanner/v5#639]
Currently one can set patterns for rules that match IPv4 addresses. According to /etc/MailScanner/rules/README, these are acceptable
```
        192.168.21.             # Any SMTP client IP address in this network
        192.168.21              # Any SMTP client IP address in this network
        192.168.21.0/255.255.255.0 # Any SMTP client IP address in this network
        192.168.21.0/24         # Any SMTP client IP address in this network
        /pattern-with-no-letters/ # Any SMTP client IP address matching this
                                  # Perl regular expression
        /^192\.168\.1[4567]\./  # Any SMTP client IP address in the networks
                                # 192.168.14 - 192.168.17
```
However, none of these allow IPv6 addresses. Even `/pattern-with-no-letters/ ` won't work as most IPv6 addresses contain letters..

I would like to be able to use patterns like
```
    2600:1700:a700:bc1f:
    /^2600:1700:a700:bc1f:/
```
to match IPv6 addresses beginning with `2600:1700:a700:bc1f:`.

**Comment by shawniverson** [comment]
I'm going to guess that that README is out of date, because I see this in Config.pm...although I'm not entirely clear on the logic...

Based on what I'm seeing, the anchor on an IPv6 address will not work. It does look like, however, that leaving the ^ anchor off results in one being implicitly added and the regex being treated as "numeric."  So, I would expect this regex to work:

/2600:1700:a700:bc1f:/

These places in the code look like they can handle ipv6:

Config.pm line 2358-2359
```
# Handle entirely numeric strings as netblocks (and allow IPv6 addresses!)
  if ($rule =~ /^[.:\dabcdef]+$/) {
```
This actually still gets treated as an entirely "numeric" string.

More ipv6 handling (or attempts to do so)...

Config.pm line 2387-2388
```
# Could be a CIDR or network range or network/netmask pair
  if ($rule =~ /^([.:\da-f]+)\s*\/\s*([.:\da-f]+)$/) {
```

Config.pm line 2402-2403
```
 if ($rule =~ /^[.:\da-f]+\s*-\s*[.:\da-f]+$/) {
    # It's a network range, e.g. 152.78.0.0-152.78.255.255
```

**Comment by msapiro** [comment]
I never actually tested, but now I have.
```
From:   /2600:1700:a700:bc1f: /   no
or
From:   /^2600:1700:a700:bc1f: .*/  no
```
doesn't work, but
```
From:   2600:1700:a700:bc1f:    no
```
without the slashes is recognized by the code at Config.pm line 2358-2359 and does work to match IPv6 addresses beginning with `2600:1700:a700:bc1f: `
