### ISSUE TITLE
LinkedIN is being blacklisted

### ISSUE THREAD

**Issue by TheGITofTeo997** [MailScanner/v5#662]
Hello, apparently LinkedIN is being blacklisted by this list.
I believe this is an error and that it should be removed
Cheers.

**Comment by shawniverson** [comment]
@TheGITofTeo997 Can you provide detail on the issue you are seeing with LinkedIn?

**Comment by TheGITofTeo997** [comment]
I am using the Phishing MailScanner Info list for my DNS AdBlock and I noticed LinkedIN is being blocked, I am sorry if this is not the right place to report this but this is the only place I found. The list in the meantime might have been updated from the moment i reported this, but I suggest you to check, thanks.

**Comment by msapiro** [comment]
Mailscanner's phishing.bad.sites.conf.master is normally updated daily from http://phishing.mailscanner.info/phishing.bad.sites.conf.gz. If I'm not mistaken, that file is built with data from https://phishtank.org/, but there are issues in that the MailScanner file keeps only the host so that phishtank may list something like `http://www.linkedin.com/path/to/phish` and this winds up as `www.linkedin.com` in MailScanner's file.

However, MailScanner's phishing.safe.sites.conf.master contains `*.linkedin.com` which should override the `www.linkedin.com` in phishing.bad.sites.conf.master. If you are using Mailscanner's phishing.bad.sites list in some non-MailScanner process, you'd be better off getting data directly from phishtank. See https://phishtank.org/developer_info.php

**Comment by shawniverson** [comment]
Confirmed safe sites overriding bad sites and LinkedIn is among them.
